from service.netEaseEncode import encrypted_request
from service.util import addToLoop,headers,session,makeMd5
from service.recommendMusicService import RecommendMusicNetEaseService
from service.recommendMusicDetailService import RecommendMusicDetailNetEaseService
from service.searchMusicService import SearchMusicNetEaseService