from widgets.content.recommendMusic import RecommendMusic
from widgets.content.recommendMusicDetail import RecommendMusicDetailNetEase,RecommendMusicDetailQQ
from widgets.content.searchMusic import SearchMusic